// import Image from "next/image";
// import Hero from "../components/Hero/Hero";
import Hero from "@/components/Hero2/Hero2"
import Speciality from "@/components/Hero2/Speciality"
import Statistics from "@/components/Hero2/Statistics"

import Head from "next/head";
import  CTA  from "@/components/appointments/CTA";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Tailwind Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      <Speciality/>
      <Statistics/>
      <CTA />
      {/* Other components and content */}
    </div>
  );
}
